#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int game_over = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int note = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int PorteJeu = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int button1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int button2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button3 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int game_over = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Knocks = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Launch = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main1 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main3 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Note = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Note1 = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int carta = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Click = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int feuille = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Porte = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Sons_ambiance = 2130968580;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
